name: Build and Notify on Version Change

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: read

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version-changed: ${{ steps.check.outputs.changed }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Check if version changed
        id: check
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          PREVIOUS_VERSION=$(git show HEAD~1:package.json | node -p "JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8')).version")
          echo "Current version: $CURRENT_VERSION"
          echo "Previous version: $PREVIOUS_VERSION"
          
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "Version unchanged"
          fi
          
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

  build-windows:
    needs: check-version
    if: needs.check-version.outputs.version-changed == 'true'
    runs-on: windows-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build Windows AMD64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist:win:x64
      
      - name: Build Windows ARM64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist:win:arm
      
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.check-version.outputs.version }}
          release_name: MSS Downloader v${{ needs.check-version.outputs.version }}
          body: Automated release for version ${{ needs.check-version.outputs.version }}
          draft: false
          prerelease: false
      
      - name: Upload AMD64 Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/Abba Ababus (MSS Downloader) Setup ${{ needs.check-version.outputs.version }}-x64.exe
          asset_name: Abba.Ababus.MSS.Downloader.Setup.${{ needs.check-version.outputs.version }}-x64.exe
          asset_content_type: application/octet-stream
        continue-on-error: true
      
      - name: Upload ARM64 Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/Abba Ababus (MSS Downloader) Setup ${{ needs.check-version.outputs.version }}-arm64.exe
          asset_name: Abba.Ababus.MSS.Downloader.Setup.${{ needs.check-version.outputs.version }}-arm64.exe
          asset_content_type: application/octet-stream
        continue-on-error: true
      
      - name: Upload Windows AMD64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-amd64-build-v${{ needs.check-version.outputs.version }}
          path: release/*x64*.exe
          
      - name: Upload Windows ARM64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-arm64-build-v${{ needs.check-version.outputs.version }}
          path: release/*arm64*.exe

  build-linux:
    needs: [check-version, build-windows]
    if: needs.check-version.outputs.version-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build Linux AppImage
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist:linux
      
      - name: Upload Linux AppImage Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.build-windows.outputs.upload_url }}
          asset_path: release/Abba Ababus (MSS Downloader)-${{ needs.check-version.outputs.version }}.AppImage
          asset_name: Abba.Ababus.MSS.Downloader.${{ needs.check-version.outputs.version }}.AppImage
          asset_content_type: application/octet-stream
        continue-on-error: true
      
      - name: Upload Linux AppImage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage-build-v${{ needs.check-version.outputs.version }}
          path: release/*.AppImage

  notify:
    needs: [check-version, build-windows, build-linux]
    if: needs.check-version.outputs.version-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Telegram bot dependencies
        run: |
          cd telegram-bot
          npm install
      
      - name: Send Multiplatform Telegram notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd telegram-bot
          npm run send-multiplatform-build